version: '3.3'

services:
    postgres:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=SushiRoom
            - POSTGRES_PASSWORD=SushiRoom
            - POSTGRES_DB=SushiRoomDB
        expose:
            - "5432"
        ports:
            - "5432:5432"
        env_file:
            - database\.env
    
    app:
      restart: always
      ports:
        - "3000:3000"
      build:
        context: database\
      environment:
        - DB_HOST=postgres
        - DB_PORT=5432
      env_file:
        - database\.env
      depends_on:
        - postgres
    
    bot:
      restart: always
      build:
        context: telegram_bot
      env_file:
        - telegram_bot\.env

volumes:
    postgres_data: