version: '3.3'

services:
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "5432:5432"
        env_file:
            - database/.env
    
    backend:
        build:
            context: database/
            dockerfile: Dockerfile
        container_name: sushiroombot_backend
        restart: always
        depends_on:
            - db
        expose:
            - "8000"
        ports:
            - "8000:8000"
        env_file:
            - database/.env

    bot:
        restart: always
        build:
            context: telegram_bot
        env_file:
            - telegram_bot/.env

volumes:
    postgres_data: