"""First migration

Revision ID: cd9b6fdcd28a
Revises: 
Create Date: 2023-11-10 13:27:06.680240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = 'cd9b6fdcd28a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('picture', sqlalchemy_file.types.ImageField(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('file', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegramuser',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('birth_day', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegramuser')
    op.drop_table('sale')
    op.drop_table('promotion')
    # ### end Alembic commands ###
